version: "3"
services:
  gtdent:
    container_name: gtdent
    build: .
    restart: always
    env_file:
      - .env.local
    network_mode: host
    networks:
      - router-network
      - app-network


networks:
  router-network:
    external: true
  host:
    external: true