version: "3"
services:
  gtdent:
    container_name: gtdent
    build: .
    restart: always
    env_file:
      - .env.local
    networks:
      - router-network
      - mynetwork


networks:
  router-network:
    external: true
  mynetwork:
    driver: bridge